"""Unit tests for the PROV-O (PROV-JSON) interchange export (ponens.prov)."""

from ponens.prov import to_prov_json


def _trace():
    return {
        "trace_id": "tr1", "spec_version": "1.9", "assistant": "codelogician", "model": "opus",
        "timestamp": "2026-01-01T00:00:00Z",
        "actions": [
            {"id": 1, "category": "reasoning", "type": "Formalize", "label": "build model", "inputs": []},
            {"id": 2, "category": "reasoning", "type": "Verify", "label": "prove", "inputs": ["g1"]},
        ],
        "artifacts": [
            {"artifact_id": "m1", "artifact_type": "FormalModel", "producer_action_id": 1, "name": "model v1"},
            {"artifact_id": "m2", "artifact_type": "FormalModel", "producer_action_id": 1,
             "supersedes": "m1", "name": "model v2"},
            {"artifact_id": "g1", "artifact_type": "VerificationGoal", "producer_action_id": 1,
             "derived_from": ["m1"]},
            {"artifact_id": "vr1", "artifact_type": "VerificationResult", "producer_action_id": 2,
             "derived_from": ["g1"], "payload": {"status": "proved"}},
            {"artifact_id": "r1", "artifact_type": "Residual", "derived_from": ["vr1"],
             "payload": {"kind": "defeater", "defeater_kind": "rebuts", "severity": "critical", "status": "open"}},
        ],
    }


def test_prefix_and_top_level_shape():
    d = to_prov_json(_trace())
    assert d["prefix"]["prov"].startswith("http://www.w3.org/ns/prov#")
    assert "ponens" in d["prefix"]
    for k in ("entity", "activity", "agent", "wasGeneratedBy", "used", "wasDerivedFrom",
              "wasAttributedTo", "wasAssociatedWith"):
        assert k in d, f"missing {k}"


def test_artifacts_become_entities_actions_activities():
    d = to_prov_json(_trace())
    assert "ponens:m1" in d["entity"] and "ponens:vr1" in d["entity"]
    assert d["entity"]["ponens:m1"]["prov:type"] == "ponens:FormalModel"
    assert "ponens:act-1" in d["activity"] and "ponens:act-2" in d["activity"]
    assert d["activity"]["ponens:act-2"]["prov:type"] == "ponens:reasoning/Verify"


def test_generation_usage_derivation():
    d = to_prov_json(_trace())
    # vr1 was generated by action 2
    assert any(v == {"prov:entity": "ponens:vr1", "prov:activity": "ponens:act-2"}
               for v in d["wasGeneratedBy"].values())
    # action 2 used g1
    assert any(v == {"prov:activity": "ponens:act-2", "prov:entity": "ponens:g1"}
               for v in d["used"].values())
    # vr1 wasDerivedFrom g1
    assert any(v.get("prov:generatedEntity") == "ponens:vr1" and v.get("prov:usedEntity") == "ponens:g1"
               for v in d["wasDerivedFrom"].values())


def test_supersedes_is_a_revision():
    d = to_prov_json(_trace())
    revs = [v for v in d["wasDerivedFrom"].values() if v.get("prov:type") == "prov:Revision"]
    assert revs == [{"prov:generatedEntity": "ponens:m2", "prov:usedEntity": "ponens:m1",
                     "prov:type": "prov:Revision"}]


def test_native_semantics_ride_as_ponens_attrs():
    d = to_prov_json(_trace())
    r = d["entity"]["ponens:r1"]
    assert r["prov:type"] == "ponens:Residual"
    assert r["ponens:kind"] == "defeater" and r["ponens:defeater_kind"] == "rebuts"
    assert r["ponens:severity"] == "critical"
    assert d["entity"]["ponens:vr1"]["ponens:verdict"] == "proved"


def test_trace_is_a_bundle_attributed_to_the_agent():
    d = to_prov_json(_trace())
    b = d["entity"]["ponens:trace-tr1"]
    assert b["prov:type"] == "prov:Bundle"
    assert b["prov:generatedAtTime"] == "2026-01-01T00:00:00Z"
    agent_ids = set(d["agent"])
    assert any(v["prov:entity"] == "ponens:trace-tr1" and v["prov:agent"] in agent_ids
               for v in d["wasAttributedTo"].values())
    assert d["agent"][next(iter(agent_ids))].get("ponens:model") == "opus"
