"""The trace wire schema - Trace Spec 1.15 as JSON Schema - and checking a trace against it.

`trace.v1_15.json` is the interchange projection of the newest spec (§16) as ponens reads and writes it,
generated by `tools/build_trace_schema.py`. 1.15 only adds to 1.14 - every valid 1.14 trace is a valid
1.15 one - so a trace of either version is checked against it; `trace.v1_14.json`, the 1.14 projection,
is shipped beside it unchanged for implementations that pin 1.14. `validate_trace` stays the structural check every command
relies on; this is the wire check `trace validate` adds when `jsonschema` is installed (the `schema`
extra), and what any other implementation can validate against.
"""

import functools
import json
import pathlib

SCHEMA_PATH = pathlib.Path(__file__).with_name("trace.v1_15.json")
SPEC_VERSION = "1.15"
V1_14_PATH = pathlib.Path(__file__).with_name("trace.v1_14.json")


@functools.lru_cache(maxsize=1)
def load():
    return json.loads(SCHEMA_PATH.read_text())


def available():
    """Is `jsonschema` importable? It is optional: `pip install ponens[schema]`."""
    try:
        import jsonschema  # noqa: F401
    except ImportError:
        return False
    return True


def _where(path):
    out = ""
    for p in path:
        out += f"[{p}]" if isinstance(p, int) else (f".{p}" if out else str(p))
    return out or "(trace)"


def _leaves(err):
    """What is actually wrong: through an `option` (a value or null), the value branch's errors."""
    inner = [e for e in (err.context or []) if not (e.validator == "type" and e.validator_value == "null")]
    return [x for e in inner for x in _leaves(e)] if inner else [err]


def schema_errors(trace, schema=None):
    """Every way `trace` fails the wire schema, as `schema: <where>: <what>` lines - or None when
    `jsonschema` is not installed (the check is then skipped, never silently passed: callers say so)."""
    if not available():
        return None
    import jsonschema
    v = jsonschema.Draft202012Validator(schema or load())
    out = []
    for e in sorted(v.iter_errors(trace), key=lambda e: [(0, p, "") if isinstance(p, int) else (1, 0, str(p)) for p in e.absolute_path]):
        for leaf in _leaves(e):
            line = f"schema: {_where(leaf.absolute_path)}: {leaf.message}"
            if line not in out:
                out.append(line)
    return out
